### ISSUE TITLE
SQLite client issue with local facts

### ISSUE THREAD

**Issue by zeldafreak** [jinaga/jinaga.net#107]
I don't yet have a minimum-viable reproduction of this issue, but wanted to get this reported so you could add it to your backlog.

My application is using `JinagaClient.Local.Fact` to save a fact (`Qma.Order.Saved`) to the SQLite client, and I'm finding that some `JinagaClient.Local.Query` calls work when there are no results, but then begin to fail after I add data that should be returned. Others continue to work just fine. I suspect the one that is not working is because it accepts two givens.

```csharp
/// <summary>Represents an organization, or business unit within an organization, that might need separate data.</summary>
[FactType("Qma.Company")]
public record Company(string Id)

/// <summary>Represents a deployment environment.</summary>
[FactType("Qma.AppEnvironment")]
public record AppEnvironment(Company Company, string Id);

/// <summary>A unique identifier representing the current device.</summary>
[FactType("Qma.DeviceId")]
public record DeviceId(AppEnvironment Environment, string Value);

/// <summary>A predecessor fact that represents unsynchronized state on this device.</summary>
[FactType("Qma.DeviceSession")]
public record DeviceSession(DeviceId DeviceId, string SessionId);

[FactType("Qma.Order.Details")]
public record OrderDetails(
    /* ...snip... this fact is quite large */
)

[FactType("Qma.Order.Saved")]
public record SavedOrder(
    DeviceSession Session,
    OrderDetails Details,
    UserName SavedBy,
    DateTime SavedOn,
    SavedOrder[] History
);
```

When I attempt to get all the `SavedOrders` in the current session, it works just fine. Here's the spec for that:
```
let session: Qma.DeviceSession = #fBpSXHZx1vvLxfpRbRLaYVFIgcJLNEHw51/qqyJXx3gbfmDMboM/JfkvABHaJl2XVyQm5/1jH55BBdnu6hRVjg==
  
  (session: Qma.DeviceSession) {
      saved: Qma.Order.Saved [
          saved->Session: Qma.DeviceSession = session
          !E {
              s: Qma.Order.Saved [
                  s->History: Qma.Order.Saved = saved
              ]
          }
          !E {
              or: Qma.Order.Received [
                  or->Order: Qma.Order = saved->Details: Qma.Order.Details->Order: Qma.Order
              ]
          }
      ]
  } => saved
```

But if I try to get all the saved orders with a specific `Qma.Order.Source.Key`, it fails:
```
let session: Qma.DeviceSession = #fBpSXHZx1vvLxfpRbRLaYVFIgcJLNEHw51/qqyJXx3gbfmDMboM/JfkvABHaJl2XVyQm5/1jH55BBdnu6hRVjg==
let school: Qma.Order.Source.Key = #cIYau0tluF5jqW19HTpjTYNrdl5dp10IODC7/kDBstEbWEe97gn0aFaoi5coVG1WYtyDlc7WihHU+nIKxapQ1w==
  
  (session: Qma.DeviceSession, school: Qma.Order.Source.Key) {
      saved: Qma.Order.Saved [
          saved->Session: Qma.DeviceSession = session
          saved->Details: Qma.Order.Details->School: Qma.Order.Source.Key = school
          !E {
              s: Qma.Order.Saved [
                  s->History: Qma.Order.Saved = saved
              ]
          }
          !E {
              s: Qma.Order.Received [
                  s->Order: Qma.Order = saved->Details: Qma.Order.Details->Order: Qma.Order
              ]
          }
      ]
  } => saved
```

The error I receive is:
```
	System.ArgumentException: Neither predecessor nor successor fact has been written
	   at Jinaga.Store.SQLite.Generation.SqlGenerator.GenerateJoins(ImmutableList`1 edges, HashSet`1 writtenFactIndexes)
	   at Jinaga.Store.SQLite.Generation.SqlGenerator.GenerateResultSqlQuery(QueryDescription queryDescription)
	   at Jinaga.Store.SQLite.Generation.SqlGenerator.CreateSqlQueryTree(ResultDescription description, Int32 parentFactIdLength)
	   at Jinaga.Store.SQLite.SQLiteStore.Jinaga.Services.IStore.Read(FactReferenceTuple givenTuple, Specification specification, CancellationToken cancellationToken)
	   at Jinaga.Managers.FactManager.QueryLocal(FactReferenceTuple givenTuple, Specification specification, CancellationToken cancellationToken)
	   at Jinaga.LocalJinagaClient.<RunSpecification>d__14`1[[Qma.Shared.Facts.SavedOrder, Qma.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
	   at Jinaga.LocalJinagaClient.<Query>d__5`3[[Qma.Shared.Facts.DeviceSession, Qma.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Qma.Shared.Facts.OrderSourceKey, Qma.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Qma.Shared.Facts.SavedOrder, Qma.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
```

**Comment by michaellperry** [comment]
Fixed in PR #108
