### ISSUE TITLE
Any tips for getting F# working?

### ISSUE THREAD

**Issue by njlr** [jinaga/jinaga.net#137]
I tried playing with the example code:

```fsharp
#r "nuget: Jinaga, 1.0.6"

open System.Linq
open Jinaga

[<FactType("Corporate.Company")>]
type Company =
  {
    Identifier : string
  }

[<FactType("Corporate.Employee")>]
type Employee =
  {
    Company : Company
    EmployeeNumber : int
  }

let employeesOfCompany =
  Given<Company>.Match(
    (fun (company : Company) (facts : Repository.FactRepository) ->
      facts.OfType<Employee>().Where(fun x -> x.Company = company))
  )

let j = JinagaClient.Create()

let employees = j.Query(employeesOfCompany, { Identifier = "Contoso" }).Result

for employee in employees do
  printfn $"%A{employee}"
```

But when I run it I hit a run-time error:

```
System.ArgumentException: Expected a unary lambda expression for QuotationToLambdaExpression(SubstHelper(NewDelegate (Func`2, x, x), new [] {}, new [] {})).
   at Jinaga.Repository.SpecificationProcessor.GetLambda(Expression argument)
   at Jinaga.Repository.SpecificationProcessor.ProcessSource(Expression expression, SymbolTable symbolTable, String recommendedLabel)
   at Jinaga.Repository.SpecificationProcessor.Queryable[TProjection](LambdaExpression specExpression)
   at Jinaga.Given`1.Match[TProjection](Expression`1 specExpression)
```

I'm not at all familiar with `Expression` so unsure where I went wrong here. 

Any ideas?

(You can paste this into an `fsx` file then run with `dotnet fsi ./Repro.fsx`)

**Comment by michaellperry** [comment]
That's awesome! I love how this looks in F#.

Let me work on this for a few days. I think I can extend the expression parser to accept the tree that F# produces.

If you want to give it a try yourself, clone the project and put a breakpoint in `Jinaga/Repository/SpecificationProcessor.cs` in the `GetLambda` method. Then run the unit test in `Jinaga.Test/Specifications/SpecificationTest.cs` called `CanSpecifySuccessors`. Once you hit that breakpoint and have a look around, you can write an F# version of the unit test. See what's different.

I'll let you know what I find.

**Comment by michaellperry** [comment]
When I got the code in the debugger, I found that the expression had the following structure:

```
.Call System.Linq.Queryable.Where(
    .Call $facts.OfType(),
    .Call Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.QuotationToLambdaExpression(
        .Call Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.SubstHelper(
            .Constant<Microsoft.FSharp.Quotations.FSharpExpr>(NewDelegate (Func`2, x,
             Call (None, op_Equality,
                   [PropertyGet (Some (x), Company, []), company]))),
            .NewArray Microsoft.FSharp.Quotations.FSharpVar[] {
                .Constant<Microsoft.FSharp.Quotations.FSharpVar>(company)
            },
            .NewArray System.Object[] {
                (System.Object)$company
            }
        )
    )
)
```

It looks like there are ways to turn F# quotations into C# expressions, but I'm not familiar with them. For example [F# Quotation Evaluator](https://fsprojects.github.io/FSharp.Quotations.Evaluator/). This might take a while.

**Comment by michaellperry** [comment]
Pushed branch `fsharp-tests`

**Comment by michaellperry** [comment]
Making progress! The following test passes:

```fsharp[<Fact>]
let CanSpecifyIdentity() =
    let specification = Given<Airline>.Select(
        <@ Func<Airline, FactRepository, Airline>(fun airline facts -> airline) @>
    )
    Assert.Equal(
        """(airline: Skylane.Airline) {
} => airline
""",
        specification.ToString().ReplaceLineEndings()
    )
```

I must clarify that the `Given<T>.Select` used in that test is not the one published by the C# library. I needed to express types in F# that have no C# equivalent in order to make that interface work. So I wrote a small wrapper in F#.

I hope I can get rid of the `Func<TFact, FactRepository, TProjection>` syntax. Projections tend to be complex types. It would be better to let type inference figure that out.

Update pushed to the `fsharp-tests` branch.

**Comment by michaellperry** [comment]
It turns out that F# will translate the Expr to Expression in this specific case. The syntax is much simplified, the projection type is inferred, and this test passes with the regular `Given<T>.Select`:

```fsharp
[<Fact>]
let CanSpecifyIdentity() =
    let specification = Given<Airline>.Select(
        fun airline facts -> airline
    )
    Assert.Equal(
        """(airline: Skylane.Airline) {
} => airline
""",
        specification.ToString().ReplaceLineEndings()
    )
```

**Comment by michaellperry** [comment]
It appears that the core issue is that F# only translates the initial Expr, [not nested Exprs](https://github.com/dotnet/fsharp/issues/2758). This is apparently a fairly common complaint with respect to F# and ORMs.

It looks like the direction that the F# language is taking is to use query syntax. So I think we should focus on making this syntax work:

```fsharp
let employeesOfCompany =
    Given<Company>.Match<Employee>(
        fun company facts ->
            query {
                for employee in facts.OfType<Employee>() do
                where (employee.Company = company)
                select employee
            }
    )
```

What are your thoughts?

**Comment by njlr** [comment]
> It appears that the core issue is that F# only translates the initial Expr, [not nested Exprs](https://github.com/dotnet/fsharp/issues/2758). This is apparently a fairly common complaint with respect to F# and ORMs.
> 
> It looks like the direction that the F# language is taking is to use query syntax. So I think we should focus on making this syntax work:
> 
> ```fsharp
> let employeesOfCompany =
>     Given<Company>.Match<Employee>(
>         fun company facts ->
>             query {
>                 for employee in facts.OfType<Employee>() do
>                 where (employee.Company = company)
>                 select employee
>             }
>     )
> ```
> 
> What are your thoughts?

This does look nice, and it mirrors the C# version too :+1:

**Comment by njlr** [comment]
Sorry just circling back on this:

```fsharp
#r "nuget: Jinaga, 1.1.39"

open Jinaga

[<FactType("Corporate.Company")>]
type Company =
  {
    Identifier : string
  }

[<FactType("Corporate.Employee")>]
type Employee =
  {
    Company : Company
    EmployeeNumber : int
  }

let employeesOfCompany =
  Given<Company>.Match<Employee>(
    fun company facts ->
      query {
        for employee in facts.OfType<Employee>() do
        where (employee.Company = company)
        select employee
      }
  )

let j = JinagaClient.Create()

let employees = j.Query(employeesOfCompany, { Identifier = "Contoso" }).Result

for employee in employees do
  printfn $"%A{employee}"
```

> System.InvalidOperationException: variable 'company' of type 'FSI_0002+Company' referenced from scope '', but it is not defined

Is there a way to build a `Specification` outside of LINQ?

**Comment by michaellperry** [comment]
There is an internal builder that the LINQ query provider uses. It's not intended to be human readable, but it can be expressed as a tree of function calls. [This test](https://github.com/jinaga/jinaga.net/blob/main/Jinaga.Test/Specifications/LinqProcessorTest.cs#L338) uses it in that way in order to validate the output.

Let me know if this is the direction you are exploring.
