### ISSUE TITLE
Query throws when offline, even when SQLite is configured

### ISSUE THREAD

**Issue by michaellperry** [jinaga/jinaga.net#75]
The Query method should fall back to local storage while offline:

```
60|2024-02-20T14:04:49.6032740+00:00|ERROR|1|PostListViewModel|Error while handling edit --> System.Net.Http.HttpRequestException: The Internet connection appears to be offline.
 ---> Foundation.NSErrorException: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x280499e60 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=Resolved 0 endpoints in 1ms using unknown from cache, _NSURLErrorNWPathKey=unsatisfied (No network route)}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <5C7FEB0A-EA19-4B09-AE06-27DA47D2D64F>.<20>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <5C7FEB0A-EA19-4B09-AE06-27DA47D2D64F>.<20>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=https://repdev.jinaga.com/N25EVWOs91edOIao79xosTUjEpDHF4HrxOx0GrpZtbMq3ZHqu7DyeiDmEgmhnbBLTdQCBS79OzdzOzTRLi54VQ/feeds, NSErrorFailingURLKey=https://repdev.jinaga.com/N25EVWOs91edOIao79xosTUjEpDHF4HrxOx0GrpZtbMq3ZHqu7DyeiDmEgmhnbBLTdQCBS79OzdzOzTRLi54VQ/feeds, _kCFStreamErrorDomainKey=1}
   Exception_EndOfInnerExceptionStack
   at System.Net.Http.NSUrlSessionHandler.SendAsync(HttpRequestMessage , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at Jinaga.Http.HttpConnection.<WithHttpClient>d__10`1[[Jinaga.Http.FeedsResponse, Jinaga, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Jinaga.Http.HttpNetwork.Feeds(FactReferenceTuple givenTuple, Specification specification, CancellationToken cancellationToken)
   at Jinaga.Managers.NetworkManager.Fetch(FactReferenceTuple givenTuple, Specification specification, CancellationToken cancellationToken)
   at Jinaga.Managers.FactManager.Fetch(FactReferenceTuple givenTuple, Specification specification, CancellationToken cancellationToken)
   at Jinaga.JinagaClient.<RunSpecification>d__26`1[[BlogMaui.Areas.Blog.SiteName, BlogMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Jinaga.JinagaClient.<Query>d__13`2[[BlogMaui.Areas.Blog.Site, BlogMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[BlogMaui.Areas.Blog.SiteName, BlogMaui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at BlogMaui.Areas.Blog.Posts.PostListViewModel.HandleEdit()
```

**Comment by michaellperry** [comment]
On further analysis, this appears to be the correct behavior. If the intent of the code was to query with no possibility of an exception, then the coder should choose `QueryLocal`. That would also ensure no latency to attempt a connection. The fallback behavior is present in `Watch` and `Subscribe`, which both return local results more quickly and set the error status rather than throwing.
