### ISSUE TITLE
Exception in GenerateExistentialWhereClause

### ISSUE THREAD

**Issue by michaellperry** [jinaga/jinaga.net#86]
A specification can cause the following line to be hit.

https://github.com/jinaga/jinaga.net/blob/main/Jinaga.Store.SQLite/Generation/SqlGenerator.cs#L69

**Comment by michaellperry** [comment]
```
07:34:08:016       at Jinaga.Managers.NetworkManager.ProcessFeed(String feed, CancellationToken cancellationToken)
07:34:08:016       at Jinaga.Managers.NetworkManager.Fetch(FactReferenceTuple givenTuple, Specification specification, CancellationToken cancellationToken) - System.NotImplementedException: The method or operation is not implemented.
07:34:08:016       at Jinaga.Store.SQLite.Generation.SqlGenerator.GenerateExistentialWhereClause(ExistentialConditionDescription existentialCondition, HashSet`1 outerFactIndexes)
07:34:08:016       at Jinaga.Store.SQLite.Generation.SqlGenerator.<>c__DisplayClass1_0.<GenerateResultSqlQuery>b__6(ExistentialConditionDescription existentialCondition)
07:34:08:016       at System.Linq.Utilities.<>c__DisplayClass2_0`3[[Jinaga.Store.SQLite.Description.ExistentialConditionDescription, Jinaga.Store.SQLite, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<CombineSelectors>b__0(ExistentialConditionDescription x)
07:34:08:016       at System.Linq.Enumerable.SelectIListIterator`2[[Jinaga.Store.SQLite.Description.ExistentialConditionDescription, Jinaga.Store.SQLite, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
07:34:08:016       at System.String.Join(String separator, IEnumerable`1 values)
07:34:08:016       at Jinaga.Visualizers.Strings.Join[String](IEnumerable`1 elements, String separator)
07:34:08:016       at Jinaga.Store.SQLite.Generation.SqlGenerator.GenerateResultSqlQuery(QueryDescription queryDescription)
07:34:08:016       at Jinaga.Store.SQLite.Generation.SqlGenerator.CreateSqlQueryTree(ResultDescription description, Int32 parentFactIdLength)
07:34:08:016       at Jinaga.Store.SQLite.SQLiteStore.Jinaga.Services.IStore.Read(FactReferenceTuple givenTuple, Specification specification, CancellationToken cancellationToken)
07:34:08:016       at Jinaga.Observers.ObservableSource.NotifyFactSaved(FactGraph graph, Fact fact, CancellationToken cancellationToken)
07:34:08:016       at Jinaga.Observers.ObservableSource.Notify(FactGraph graph, ImmutableList`1 facts, CancellationToken cancellationToken)
07:34:08:016       at Jinaga.Managers.FactManager.NotifyObservers(FactGraph graph, ImmutableList`1 facts, CancellationToken cancellationToken)
07:34:08:016       at Jinaga.JinagaClient.<.ctor>b__8_0(FactGraph graph, ImmutableList`1 added, CancellationToken cancellationToken)
07:34:08:016       at Jinaga.Managers.LoadBatch.Load(CancellationToken cancellationToken)
07:34:08:016       at Jinaga.Managers.LoadBatch.<>c__DisplayClass8_0.<<-ctor>b__0>d.MoveNext()
07:34:08:016    --- End of stack trace from previous location ---
07:34:08:016       at Jinaga.Managers.NetworkManager.ProcessFeed(String feed, CancellationToken cancellationToken)
07:34:08:016       at Jinaga.Managers.NetworkManager.Fetch(FactReferenceTuple givenTuple, Specification specification, CancellationToken cancellationToken)
```
